Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,9 +13,20 @@ jobs:
             - run : |
                 check.sh $(pwd) $(pwd)
                   if [ -s $coding-style-reports.log ]
-                      cat coding-style-reports.log
+                  cat coding-style-reports.log
+                  i=1
+                  then
+                    while read -r line
+                    do                                                                                                                                                                       
+                      tab=( ${line//:/ } )
+                      yo=(${tab[0]})
+                      str=( ${yo//// } )
+                      echo "::error file=${str[1]},line=${tab[3]},title=${tab[2]} coding style error::${tab[3]}"
+                      ((i++))
+                    done < "coding-style-reports.log"
+                    exit 2
                   else
-                      exit 0
+                    exit 0
                   fi
           
     check_program_compilation:
